name: Setup NPM

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        description: >
          The version of Node.js to install.
          Must be >= v24 for OIDC token support.
        default: "24.13.1"
        type: string
      npm-version:
        required: false
        description: >
          The version of npm to install.
          Must be >= v11.5.1 for OIDC token support.
        default: "11.9.0"
        type: string
      use-cache:
        required: false
        description: >
          Enable or disable automatic caching.
          For security reasons, caching must be set to 'false' for publishing steps.
        default: true
        type: boolean

jobs:
  setup:
    name: Setup NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          package-manager-cache: ${{inputs.use-cache}}
      - name: Install npm at specific version
        run: npm install -g npm@${{ inputs.npm-version }}
      - name: Install dependencies
        run: npm ci
