name: Lint

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '24' # >= 24 required for OIDC token support
        type: string
      npm-version:
        required: false
        default: '11.9.0' # >= v11.5.1 required for OIDC token support
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup NPM
        uses: ./.github/workflows/setup_yarn.yml
        with:
          node-version: ${{ inputs.node-version }}
          npm-version: ${{ inputs.npm-version }}
      - name: Run lint
        run: npm run lint
